name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Neos CMS image checker plugin frontend build'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build the plugin
        run: yarn build
